config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles

  get "signup",to: "users#new"
  resources :users, except: [:new]

  get 'login', to:"sessions#new"
  post 'login',to:"sessions#create"
  delete 'logout', to:"sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article <ApplicationRecord
    belongs_to :user
    validates :title, presence:true, length:{minimum:6,maximum:100}
    validates :descrition, presence:true, length:{minimum:10,maximum:300}
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length:{minimum:3,maximum:25}
end

app/models/user.rb
class User <ApplicationRecord
    before_save {self.email=email.downcase}
    has_many :articles, dependent: :destroy
    has_secure_password
    validates :username, presence:true, length:{minimum:3, maximum:25}, uniqueness: {case_sensitive:false}
    VALID_EMAIL_REGEX= /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence:true, length:{maximum:105}, uniqueness: {case_sensitive:false}, format:{with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user,:logged_in?

    def logged_in?
        !!current_user
    end

    def current_user
        if session[:user_id]
            @current_user ||=User.find(session[:user_id])
        end
    end

    def require_user
        if !logged_in?
            flash[:alert]="You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only:[:show,:update,:destroy,:edit]
    before_action :require_user, except:[:index,:show]
    before_action :require_same_user, only:[:edit,:destroy,:update]

    def show
    end

    def index
        @articles=Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article=Article.new
    end

    def edit
    end

    def create
        @article=Article.new(article_params)
        @article.user= current_user
            if @article.save
                flash[:notice]="Article created successfully"
                redirect_to @article
            else
                render :new,status: :unprocessable_entity
            end
    end

    def update
            if @article.update(article_params)
                flash[:notice]="Article edited successfully"
                redirect_to @article
            else
                render :edit,status: :unprocessable_entity
            end
    end

    def destroy
        @article.destroy
        flash[:notice]="Article successfully Deleted"
        redirect_to articles_path,status: :see_other
    end

    private

    def set_article
        @article=Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title,:descrition,:author)
    end

    def require_same_user
        if current_user!=@article.user && !current_user.admin?
            flash[:alert]="You can edit or delete your own article"
            redirect_to articles_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController <  ApplicationController
    before_action :require_admin,only:[:new,:create]
    def new
        @category=Category.new
    end

    def index
        @categories=Category.paginate(page: params[:page],per_page: 5)
    end

    def show
        @category=Category.find(params[:id])
    end

    def create
        @category=Category.new(category_params)
        if @category.save
            flash[:notice]="Category created successfully"
            redirect_to category_path(@category)
        else
            render 'new',status: :unprocessable_entity
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert]="Only Admin can create Categories"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        if logged_in?
            redirect_to articles_path
        end
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user=User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id]=user.id
            flash[:notice]="Logged In Successfully"
            redirect_to user
        else
            flash.now[:alert]="There was something wrong with your login details"
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id]=nil
        flash[:notice]="Logged Out"
        redirect_to root_path, status: 303
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only:[:edit,:update,:show,:destroy]
    before_action :require_user, except:[:index,:show,:new,:create]
    before_action :require_same_user, only:[:edit,:destroy,:update]

    def new
        @user=User.new
    end

    def edit
    end

    def index
        @users=User.paginate(page: params[:page],per_page:5)
    end

    def show
        @articles=@user.articles.paginate(page: params[:page],per_page:5)
    end

    def create
        @user=User.new(user_params)
        if @user.save
            flash[:notice]="User signed up successfully"
            session[:user_id]=@user.id
            redirect_to articles_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        if @user.update(user_params)
            flash[:notice]="User information updated successfully"
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user.destroy
        session[:user_id]=nil if @user==current_user
        flash[:notice]="User deleted successfully"
        redirect_to articles_path,status: :see_other
    end

    private

    def user_params
        params.require(:user).permit(:username,:email,:password)
    end

    def set_user
        @user=User.find(params[:id])
    end

    def require_same_user
        if current_user!=@user && !current_user.admin?
            flash[:alert]="You can edit or delete your own account"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
    <div class="container" id="article-card">
        <div class="card text-center">
            <div class="card-header">
            <%if article.user  %>
                by <%=link_to article.user.username, user_path(article.user)%>
            <%end%>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= article.title%></h5>
                <p class="card-text"><%= article.descrition%></p>
                <%= link_to "Show", article_path(article),class:"btn btn-primary"%>
                <% if logged_in? && ( article.user==current_user || current_user.admin?)%>
                    <%= link_to "Edit", edit_article_path(article), class:"btn btn-primary"%>
                    <%= link_to "Delete", article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"},class:"btn btn-primary" %>
                <%end%>

            </div>
            <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago</small>
            </div>
        </div>
    </div>
<% end%>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>prohibited this article from being saved:</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= form_with model: @article, local:true  do |form| %>
<div>
<%= form.label :title, style: "display: block" %>
<%= form.text_field :title %>
</div>

<div>
<%= form.label :description, style: "display: block" %>
<%= form.text_area :descrition %>
</div>

<div>
<%= form.submit%>
</div>
<% end %>
<%= link_to "Back to Articles", path=articles_path %> |

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form'%>
<%= link_to "Destroy", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<div class="flickr_pagination"><%= will_paginate @articles, :container =>false%></div>

<%= render 'article'%>
<div class="flickr_pagination mb-4"><%= will_paginate @articles, :container =>false%></div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>'

app/views/articles/show.html.erb
<h1>Article Description</h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.descrition %></p>
<p><strong>Created By: </strong><%= @article.user.username if @article.user %></p>

<%= link_to "Back to Articles", path=articles_path %>
<% if logged_in? && (@article.user==current_user || current_user.admin?)%>
    <%= link_to "Edit this Article", path=edit_article_path %> |
    <%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<%end%>

app/views/categories/_category.html.erb
<% @categories.each do |category| %>
    <div class="container" id="article-card">
        <div class="card text-center">
            <div class="card-header">
            </div>
            <div class="card-body">
                <h5 class="card-title"><%=link_to category.name, category_path(category)%></h5>
                <%= link_to "Show", category_path(category),class:"btn btn-primary"%>

            </div>
            <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago</small>
            </div>
        </div>
    </div>
<% end%>

app/views/categories/_form.html.erb
<div class="alert">
    <% if @category.errors.any? %>
        <h2 class="alert-heading">prohibited this article from being saved:</h2>
        <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
</div>
<%= form_with model: @category, local:true  do |form| %>
    <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.submit%>
    </div>
<% end %>
<%= link_to "Back to Categories", path=categories_path %> |

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing all Categories</h1>
<div class="flickr_pagination"><%= will_paginate @categories, :container =>false%></div>
<%= render 'category'%>
<div class="flickr_pagination"><%= will_paginate @categories, :container =>false%></div>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>'

app/views/categories/show.html.erb
<h1>Category Description</h1>
<p><strong>Title: </strong><%= @category.name %></p>

<%= link_to "Back to Categories", path=categories_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container-fluid">
  <a class="navbar-brand" href="/">AlphaBlog</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to "Bloggers", path=users_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "About", path=about_path, class:"nav-link"%>
      </li>
      <li class="nav-item dropdown list-unstyled">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "View Articles", path=articles_path, class:"dropdown-item"%></li>
          <% if logged_in?%>
            <li><%= link_to "Create Article", path=new_article_path, class:"dropdown-item"%></li>
          <%end%>
        </ul>
      </li>
      <% if logged_in?%>
        <li class="nav-item dropdown list-unstyled">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "View Categories", path=categories_path, class:"dropdown-item"%></li>
            <% if current_user.admin?%>
              <li><%= link_to "Create Category", path=new_category_path, class:"dropdown-item"%></li>
            <%end%>
          </ul>
        </li>
      <%end%>
    </ul>
    <% if logged_in? %>
      <li class="nav-item dropdown list-unstyled">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= "(Admin) " if current_user.admin %><%=current_user.username%>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "View Profile", path=user_path(current_user), class:"dropdown-item"%></li>
            <%= link_to "Edit Profile", path=edit_user_path(current_user), class:"dropdown-item"%>
            <li><%= link_to "Delete Profile", path=user_path(current_user), class:"dropdown-item",  data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
          </li>
        </ul>
      </li>
      <%= link_to 'Log Out', logout_path, class:"btn btn-outline-success",  data: { turbo_method: :delete}%>     
    <%else%>
      <%= link_to 'Log In', login_path,class:"btn btn-outline-success"%>
      <%=link_to "Sign Up",path="/signup",class:"btn btn-outline-success"%>
  <% end%>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ALPHABlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |name,msg| %>
      <%= msg %>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>
<%= link_to "Go to Articles Listing" ,path=articles_path%> |
<%= link_to "Go to Home Page", path=root_path%>

app/views/pages/home.html.erb
<div class="container" id="homeContainer">
    <div class="jumbotron text-center">
    <h1 class="display-4">AlphaBlog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="/signup" role="button">Sign Up</a>
    </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <h2>prohibited this user from being signup:</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_with model: @user, local:true  do |form| %>
    <div>
        <%= form.label :username, style: "display: block" %>
        <%= form.text_field :username %>
    </div>

    <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
    </div>

    <div>
        <%= form.label :password, style: "display: block" %>
        <%= form.text_field :password %>
    </div>

    <div>
        <%= form.submit (@user.new_record? ? "Sign Up" : "Update Account")%>
    </div>
<% end %>
<%= link_to "Back to Users", path=users_path %> |

app/views/users/edit.html.erb
<h1>Edit Your Details</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="flickr_pagination mb-4"><%= will_paginate @users, :container =>false%></div>
<div class="container">
    <% @users.each do |user| %>
        <div class="container" id="user-card">
            <div class="card text-center">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= user.username%></h5>
                    <p class="card-text"><%= user.email%></p>
                    <%= link_to "Show", user_path(user),class:"btn btn-primary"%>
                    <% if logged_in? && (user==current_user || current_user.admin?)%>
                        <%= link_to "Edit", edit_user_path(user), class:"btn btn-primary"%>
                        <%= link_to "Delete", user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"},class:"btn btn-primary" %>
                    <%end%>

                </div>
                <div class="card-footer text-muted">
                    <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
                </div>
            </div>
        </div>
    <% end%>
</div>
<div class="flickr_pagination mb-4"><%= will_paginate @users, :container =>false%></div>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div id="user-profile">
    <h1 class="text-center mt-4"><%= @user.username%>'s profile</h1>
    <% if logged_in? && (@user==current_user || current_user.admin)%>
        <%= link_to "Edit this User", path=edit_user_path,class:"btn btn-primary" %>
        <%= link_to "Delete", user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"},class:"btn btn-primary" %>
    <%end%>
    <h3 class="text-center mt-4">Articles</h3>
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false%>
    </div>
    <%= render 'articles/article' %>
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false%>
    </div>
    <%= link_to "Back to Users", path=users_path %>
</div>